import usersSlice from "../slices/usersSlice";

export const {
  registerUser,
  registerUserSuccess,
  registerUserFailure,
  loginUser,
  loginUserSuccess,
  loginUserFailure,
  clearError,
  userDateRequest,
  userDateSuccess,
  userDateFailure,
  editUserDataRequest,
  editUserDataSuccess,
  editUserDataFailure,
  editPassportRequest,
  editPassportSuccess,
  editPassportFailure,
  fetchUserPaymentRequest,
  fetchUserPaymentSuccess,
  fetchUserPaymentFailure,
  fetchUsersRequest,
  fetchUsersSuccess,
  fetchUsersFailure,
  addUserPaymentRequest,
  addUserPaymentSuccess,
  addUserPaymentFailure,
  totalSend,
  logout,
} = usersSlice.actions;